# Generated by Django 4.2.16 on 2025-03-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="age_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("teen", "Teenager (13-19)"),
                    ("young_adult", "Young Adult (20-35)"),
                    ("middle_aged", "Middle-Aged (36-55)"),
                    ("senior", "Senior (56+)"),
                ],
                max_length=15,
                null=True,
                verbose_name="Age Group",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="avatars/default.jpg",
                null=True,
                upload_to="avatars/",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="collected_posts",
            field=models.ManyToManyField(
                blank=True, related_name="collected_by", to="community.post"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="commented_posts",
            field=models.ManyToManyField(
                blank=True, related_name="commented_by", to="community.post"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="height",
            field=models.FloatField(blank=True, null=True, verbose_name="Height (cm)"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="liked_posts",
            field=models.ManyToManyField(
                blank=True, related_name="liked_by", to="community.post"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Nickname"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="weight",
            field=models.FloatField(blank=True, null=True, verbose_name="Weight (kg)"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
