# Generated by Django 4.2.16 on 2025-03-08 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_age_group_userprofile_avatar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="bio",
        ),
    ]
