# Generated by Django 4.2.16 on 2025-03-08 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_userprofile_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="date_of_birth",
        ),
    ]
