# Generated by Django 4.2.16 on 2025-03-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_userprofile_date_of_birth"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(
                blank=True,
                default="Mysterious User",
                max_length=50,
                null=True,
                verbose_name="Nickname",
            ),
        ),
    ]
