# Generated by Django 5.1.6 on 2025-03-12 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_userprofile_commented_posts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="weight",
        ),
    ]
