# Generated by Django 5.1.6 on 2025-03-20 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DummyAnalysisModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dummy_field",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Dummy Field"
                    ),
                ),
                (
                    "analysis_date",
                    models.DateField(auto_now_add=True, verbose_name="Analysis Date"),
                ),
                (
                    "analysis_score",
                    models.FloatField(default=0.0, verbose_name="Analysis Score"),
                ),
                (
                    "is_completed",
                    models.BooleanField(default=False, verbose_name="Is Completed"),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("basic", "Basic Analysis"),
                            ("advanced", "Advanced Analysis"),
                            ("custom", "Custom Analysis"),
                        ],
                        default="basic",
                        max_length=20,
                        verbose_name="Analysis Type",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Additional Notes"),
                ),
            ],
            options={
                "verbose_name": "Dummy Analysis Model",
                "verbose_name_plural": "Dummy Analysis Models",
                "ordering": ["-analysis_date"],
                "managed": False,
            },
        ),
    ]
