# Generated by Django 5.1.6 on 2025-03-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_alter_post_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="collections",
        ),
        migrations.RemoveField(
            model_name="post",
            name="images",
        ),
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
