# Generated by Django 4.2.16 on 2025-03-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Symptom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="menstrualrecord",
            name="notes",
        ),
        migrations.AddField(
            model_name="menstrualrecord",
            name="blood_volume",
            field=models.CharField(
                choices=[("light", "Light"), ("medium", "Medium"), ("heavy", "Heavy")],
                default="medium",
                max_length=10,
                verbose_name="Blood Volume",
            ),
        ),
        migrations.AddField(
            model_name="menstrualrecord",
            name="clotting",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("small", "Few Small Clots"),
                    ("large", "Many or Large Clots"),
                ],
                default="none",
                max_length=10,
                verbose_name="Clotting",
            ),
        ),
        migrations.AddField(
            model_name="menstrualrecord",
            name="mood_swings",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("mild", "Mild"),
                    ("moderate", "Moderate"),
                    ("severe", "Severe"),
                ],
                default="none",
                max_length=10,
                verbose_name="Mood Swings",
            ),
        ),
        migrations.AddField(
            model_name="menstrualrecord",
            name="stress_level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
                verbose_name="Stress Level",
            ),
        ),
        migrations.AlterField(
            model_name="menstrualrecord",
            name="end_date",
            field=models.DateField(verbose_name="End Date"),
        ),
        migrations.AlterField(
            model_name="menstrualrecord",
            name="start_date",
            field=models.DateField(verbose_name="Start Date"),
        ),
        migrations.AddField(
            model_name="menstrualrecord",
            name="menstrual_symptoms",
            field=models.ManyToManyField(
                blank=True, related_name="menstrual", to="records.symptom"
            ),
        ),
        migrations.AddField(
            model_name="menstrualrecord",
            name="post_menstrual_symptoms",
            field=models.ManyToManyField(
                blank=True, related_name="post_menstrual", to="records.symptom"
            ),
        ),
        migrations.AddField(
            model_name="menstrualrecord",
            name="pre_menstrual_symptoms",
            field=models.ManyToManyField(
                blank=True, related_name="pre_menstrual", to="records.symptom"
            ),
        ),
    ]
