# Generated by Django 4.2.16 on 2025-03-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0002_symptom_remove_menstrualrecord_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menstrualrecord",
            name="menstrual_symptoms",
        ),
        migrations.RemoveField(
            model_name="menstrualrecord",
            name="post_menstrual_symptoms",
        ),
        migrations.RemoveField(
            model_name="menstrualrecord",
            name="pre_menstrual_symptoms",
        ),
        migrations.AddField(
            model_name="menstrualrecord",
            name="symptom_description",
            field=models.TextField(blank=True, verbose_name="Additional Symptoms"),
        ),
        migrations.AlterField(
            model_name="menstrualrecord",
            name="clotting",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("small", "Few Small Clots"),
                    ("large", "Many or Large Clots"),
                ],
                max_length=10,
                verbose_name="Clotting",
            ),
        ),
        migrations.AlterField(
            model_name="menstrualrecord",
            name="mood_swings",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("mild", "Mild"),
                    ("moderate", "Moderate"),
                    ("severe", "Severe"),
                ],
                max_length=10,
                verbose_name="Mood Swings",
            ),
        ),
        migrations.AlterField(
            model_name="menstrualrecord",
            name="stress_level",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                max_length=10,
                verbose_name="Stress Level",
            ),
        ),
        migrations.DeleteModel(
            name="Symptom",
        ),
    ]
