# Generated by Django 5.1.6 on 2025-03-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("records", "0004_menstrualrecord_menstrual_symptoms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menstrualrecord",
            name="weight",
            field=models.FloatField(default=60, verbose_name="Weight (kg)"),
            preserve_default=False,
        ),
    ]
